name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Optional: keep only if your repo contains a project ZIP at the root
      - name: Unzip project if archive found
        run: |
          set -e
          shopt -s nullglob
          for z in *.zip; do
            echo "Unzipping $z"
            unzip -o -q "$z" -d .
          done

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept SDK Licenses
        run: yes | sdkmanager --licenses || true

      - name: Install Android platforms/build-tools
        run: |
          sdkmanager "platforms;android-35" "build-tools;35.0.0" || true

      - name: Locate project directory
        id: findproj
        shell: bash
        run: |
          set -e
          PROJECT_DIR=$(dirname $(find . -maxdepth 4 -name "settings.gradle.kts" -o -name "settings.gradle" | head -n1))
          if [ -z "$PROJECT_DIR" ]; then
            echo "❌ Could not find settings.gradle(.kts)."
            ls -la
            exit 1
          fi
          echo "project_dir=$PROJECT_DIR
