- name: Patch Gradle for Kotlin 2.0 Compose
  shell: bash
  run: |
    set -e

    # 1) Add Compose compiler plugin to the root build.gradle.kts
    # (id("org.jetbrains.kotlin.plugin.compose") version "2.0.20" apply false)
    if grep -q 'id("org.jetbrains.kotlin.android") version "2.0.20" apply false' build.gradle.kts; then
      sed -i 's/id("org.jetbrains.kotlin.android") version "2.0.20" apply false/&\n    id("org.jetbrains.kotlin.plugin.compose") version "2.0.20" apply false/' build.gradle.kts
    fi

    # 2) Apply the plugin in app/build.gradle.kts
    if grep -q 'plugins {' app/build.gradle.kts; then
      sed -i 's/id("org.jetbrains.kotlin.android")/id("org.jetbrains.kotlin.android")\n    id("org.jetbrains.kotlin.plugin.compose")/' app/build.gradle.kts
    fi

    # 3) Remove the old composeOptions block (deprecated with Kotlin 2.x Compose plugin)
    awk '
      /composeOptions[[:space:]]*\{/ {skip=1}
      skip && /\}/ {skip=0; next}
      !skip {print}
    ' app/build.gradle.kts > app/build.gradle.kts.new && mv app/build.gradle.kts.new app/build.gradle.kts
